theme: jekyll-theme-minimal
title: EVE </br>Evolutionary Model of Variant Effect
description: "A model for the prediction of clinical significance of human variants based on sequences of diverse organisms across evolution</br>
   </br>
Project developed by:</br>
Jonathan Frazer*, Pascal Notin*, Mafalda Dias*, Aidan Gomez , Kelly Brock, </br>
Yarin Gal** and Debora Marks**</br>
</br>
Marks Lab - Harvard Medical School</br>
OATML - Oxford Applied and Theoretical Machine Learning Group  </br>
</br>
 </br>
  </br>
</br>"

show_downloads: false
