theme: jekyll-theme-minimal
title: EVE -- Evolutionary Model of Variant Effect
description: "A model for the prediction of clinical significance of human variants based on sequences of diverse organisms across evolution</br>
Project developed by:</br>
Jonathan Frazer, Mafalda Dias, Kelly Brock and Debora Marks at Harvard Medical School annd</br>
Pascal Notin, Aidan gomez and Yarin Gal at OATML -- Oxford Applied and Theoretical Machine Learning Group"
show_downloads: false
google_analytics:
